name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar el proyecto
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar pruebas
      run: dotnet test --configuration Release --no-restore

  docker:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Login en Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construir la imagen Docker
      run: docker build -t bpdevop/libraryconnectapi:latest -f LibraryConnectAPI/LibraryConnectAPI/Dockerfile LibraryConnectAPI/LibraryConnectAPI/

    - name: Subir la imagen a Docker Hub
      run: docker push bpdevop/libraryconnectapi:latest
